apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-uip6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-uip6
    app.kubernetes.io/part-of: integ-app-yyyd
  name: hacbs-test-project-uip6
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-uip6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-uip6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/nbe-e2e-svfl-tenant/integ-app-yyyd/hacbs-test-project-uip6@sha256:9ecb822b1c475c4ef8d4d77d2dd340395454604e8dbb3e55a753241545c1c1df
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
